name: Deploy Bicep file
on: [push]

permissions:
    id-token: write
    contents: read

jobs:
  create-resource-groups:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main
    - name: Log into Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Deploy Resource Groups
      uses: azure/arm-deploy@v1
      with:
        scope: 'subscription'
        region: 'westeurope'
        template: ./biceptemplates/avd-rgs.bicep
        failOnStdErr: false

    - name: Deploy AVD Infra
      uses: azure/arm-deploy@v1
      with: 
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./biceptemplates/avd-infra.bicep
        failOnStdErr: false

    - name: Deploy Storage Account
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./biceptemplates/main.bicep
        parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'
        failOnStdErr: false
        